# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KhunMea' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KhunMea

  target 'KhunMea-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'KhunMeaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KhunMea-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KhunMea-tvOS

  target 'KhunMea-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
